---

- name: "Update apt packages"
  become: yes
  apt:
    upgrade_cache:  yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade:  yes

- name: "install dependencies."
  become: true
  apt:
    name: ["python","nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

