- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: ~/project/.circleci/ansible/roles/deploy/files/
    dest: ~/
    remote_src: yes

- name: start pm2
  become: true
  command:
    npm install
    pm2 stop default
    pm2 start npm -- start
