- name: Create Directory
  file:
    path: ~/app
    state: directory

- name: Copy Artifact to Machine
  become: true
  copy: 
    src: artifact.tar.gz
    dest: ~/app/


- name: Test
  become: true
  shell: |
    tar -xvf ~/app/artifact.tar.gz .
  

- name: start pm2
  become: true
  command:
    cd ~/app/artifact
    npm install
    pm2 stop default
    pm2 start npm -- start
