- name: Create Directory
  file:
    path: ~/app
    state: directory

- name: Copy Artifact to Machine
  become: true
  copy: 
    src: artifact.tar.gz
    dest: ~/app/


#- name: Untar Artifact
#  become: true
 # shell: |
  #  tar -xvf ~/app/artifact.tar.gz
  

- name: Untar Artifact and Execute Node
  become: true
  shell: |
    tar -xvf ~/app/artifact.tar.gz -C ~/app
    cd ~/app
    npm install
    pm2 stop default
    pm2 start npm -- start
