version: 2.1

orbs:
  slack: circleci/slack@4.1
jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel:  C03DAJYL3SM
          event: fail
          mentions: '@Abbas'
          template: basic_fail_1
      - slack/notify:
          channel:  C03DAJYL3SM
          event: pass
          template: basic_success_1

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build Front-End
          command: |
              cd frontend
              npm install
              npm run build 
      - slack/notify:
          channel:  C03DAJYL3SM
          event: always
          mentions: '@Abbas'
          template: basic_success_1

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build Back-End
          command: |
              cd backend
              npm install
              npm run build
      - slack/notify:
          channel:  C03DAJYL3SM
          event: fail
          mentions: '@Abbas'
          template: basic_fail_1
  
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Test Front-End
          command:  |
            cd frontend
            npm install
            npm run test

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Test Back-End
          command:  |
            cd backend
            npm install
            npm run test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Audit the Front-End
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
            

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Audit the Back-End
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical
            

workflows:
  project3:
    jobs:
      - build-frontend:
          context: abbas-context
      - build-backend:
          context: abbas-context  

    #  - test-frontend:
     #     requires: [build-frontend]
     # - test-backend:
      #    requires:
      #      - build-backend
     # - scan-frontend:
      #    requires: [test-frontend]
      #- scan-backend:
       #   requires: [test-backend]
